version: '3.8'

services:
  app:
    build:
      context: .
      target: app
    restart: always
    command: /bin/bash -c 'python3 app.py'
    ports:
      - "8080:8080"
    working_dir: /mnt/app
    environment:
      PYTHONDONTWRITEBYTECODE: 1
